# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Received'), (2, 'Preparing'), (3, 'Cooking'), (4, 'On the way'), (5, 'Closed')], default=1)),
                ('size', models.PositiveSmallIntegerField(choices=[(1, 'Received'), (2, 'Preparing'), (3, 'Cooking'), (4, 'On the way'), (5, 'Closed')])),
                ('customer_name', models.CharField(max_length=128)),
                ('customer_address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('ingredients', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza'),
        ),
    ]
