# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20180307_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Received'), (2, 'Preparing'), (3, 'Cooking'), (4, 'On the way'), (5, 'Closed')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredients',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
